name: Deploy to YC

on:
  release:
    types: released

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install --production

      - name: Build project
        run: npm run build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: web-app
          path: ./dist

  deploy-testing:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: testing

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: web-app

      - name: Upload to YC storage
        uses: yc-actions/yc-obj-storage-upload@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ vars.BUCKET }}
          root: ./
          include: |
            assets
            index.html

  deploy-production:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: web-app

      - name: Upload to YC storage
        uses: yc-actions/yc-obj-storage-upload@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ vars.BUCKET }}
          root: ./
          include: |
            assets
            index.html

      - name: Purge CDN cache
        id: purge-cache
        uses: yc-actions/yc-cdn-cache@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          cdn-resource-id: ${{ vars.CDN_ID }}
