name: Deploy to YC

on:
  workflow_dispatch

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload to YC storage
        uses: yc-actions/yc-obj-storage-upload@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
          bucket: ${{ env.PRODUCTION_BUCKET }}
          root: ./dist
          include: |
            assets
            index.html
