name: Deploy to YC

on:
  release:
    types: released

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    
    - name: Build project
      run: npm run build

    - name: Put date to env
      run: echo "MY_DATE=$(date +%Y-%m-%dT%H:%M)" >> $GITHUB_ENV
    
    - name: Upload to YC storage
      uses: yc-actions/yc-obj-storage-upload@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
        bucket: ${{ secrets.BUCKET }}
        prefix: ${{ env.MY_DATE }}/
        root: ./dist
        include: | 
            assets
            index.html
